# Configuration taken from https://github.com/meltwater/docker-mesos
# https://github.com/containous/traefik/blob/master/examples/compose-marathon.yml

version: '2'
services:
  zookeeper:
    image: netflixoss/exhibitor:1.5.2
    hostname: zookeeper

  mesos_master:
    image: mesosphere/mesos-master:1.3.0
    hostname: mesosmaster
    volumes:
      - ./log/mesos/master:/var/log/mesos/master:rw
      - ./tmp/mesos/master:/var/tmp/mesos:rw
    networks:
      - woken-bridge
    environment:
      MESOS_PORT: 5050
      MESOS_ZK: 'zk://zookeeper:2181/mesos'
      MESOS_QUORUM: '1'
      MESOS_REGISTRY: 'in_memory'
      MESOS_CLUSTER: 'local'
      MESOS_HOSTNAME: 'mesosmaster.docker'
      MESOS_LOG_DIR: '/var/log/mesos/master'
    depends_on:
      - zookeeper

  mesos_slave:
    image: mesosphere/mesos-slave:1.3.0
    hostname: mesosslave
    privileged: true
    volumes:
      - ./log/mesos/slave:/var/log/mesos/slave:rw
      - ./tmp/mesos/slave:/var/tmp/mesos:rw
      - /sys:/sys
      #- /cgroup:/cgroup is it really needed for the demo? Not compatible with docker machine on MacOSX, try /sys/fs/cgroups...
      # /usr/bin/docker is needed if you're running an older docker version
      #- /usr/bin/docker:/usr/bin/docker:r
      - /var/run/docker.sock:/var/run/docker.sock:rw
    networks:
      - woken-bridge
    environment:
      MESOS_MASTER: 'zk://zookeeper:2181/mesos'
      MESOS_PORT: '5051'
      MESOS_LOG_DIR: '/var/log/mesos/slave'
      MESOS_WORK_DIR: '/var/tmp/mesos'
      MESOS_CONTAINERIZERS: 'docker,mesos'
      MESOS_EXECUTOR_REGISTRATION_TIMEOUT: '5mins'
      MESOS_EXECUTOR_SHUTDOWN_GRACE_PERIOD: '90secs'
      MESOS_DOCKER_STOP_TIMEOUT: '60secs'
      # If your workstation doesn't have a resolvable hostname/FQDN then $MESOS_HOSTNAME needs to be set to its IP-address
      MESOS_HOSTNAME: 'mesosslave.docker'
      MESOS_SWITCH_USER: 0
      # see bug resolution for "Failed to determine the hierarchy where the subsystem freezer is attached" at https://github.com/eBayClassifiedsGroup/PanteraS/issues/142
      MESOS_LAUNCHER: "posix"
    depends_on:
      - zookeeper
      - mesos_master

  chronos:
    image: mesosphere/chronos:chronos-2.5.0-0.1.20170628182950.ubuntu1404-mesos-1.3.0
    command: '/usr/bin/chronos run_jar --http_port 4400 --zk_hosts zookeeper:2181 --master zk://zookeeper:2181/mesos'
    hostname: chronos
    networks:
      - woken-bridge
    depends_on:
      - zookeeper
      - mesos_slave

  # Expose the database to the host
  db:
    image: postgres:9.6.5-alpine
    ports:
      - "5432:5432"
    hostname: db
    networks:
      - woken-bridge
    environment:
      POSTGRES_PASSWORD: test

  wait_dbs:
    image: "waisbrot/wait"
    restart: "no"
    networks:
      - woken-bridge
    environment:
      - TARGETS=db:5432

  create_dbs:
    image: "hbpmip/create-databases:1.0.0"
    restart: "no"
    networks:
      - woken-bridge
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_ADMIN_USER: postgres
      DB_ADMIN_PASSWORD: test
      DB1: meta
      USER1: meta
      PASSWORD1: metapwd
      DB2: features
      USER2: features
      PASSWORD2: featurespwd
      DB3: woken
      USER3: woken
      PASSWORD3: wokenpwd
    depends_on:
      - db

  meta_db_setup:
    image: "hbpmip/sample-meta-db-setup:0.2.0"
    container_name: "meta-db-setup"
    restart: "no"
    networks:
      - woken-bridge
    environment:
      FLYWAY_DBMS: postgresql
      FLYWAY_HOST: db
      FLYWAY_PORT: 5432
      FLYWAY_DATABASE_NAME: meta
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: test
    depends_on:
      - db

  sample_db_setup:
    image: "hbpmip/sample-data-db-setup:0.3.2"
    container_name: "data-db-setup"
    restart: "no"
    networks:
      - woken-bridge
    environment:
      FLYWAY_DBMS: postgresql
      FLYWAY_HOST: db
      FLYWAY_PORT: 5432
      FLYWAY_DATABASE_NAME: features
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: test
    depends_on:
      - db

  woken_db_setup:
    image: "hbpmip/woken-db-setup:1.0.2"
    container_name: "woken-db-setup"
    restart: "no"
    networks:
      - woken-bridge
    environment:
      FLYWAY_DBMS: postgresql
      FLYWAY_HOST: db
      FLYWAY_PORT: 5432
      FLYWAY_DATABASE_NAME: woken
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: test
    depends_on:
      - db

  woken:
    image: hbpmip/woken:latest
    volumes:
      - ./woken/config:/opt/woken/config
      - ./woken/lib:/opt/woken/lib
    ports:
      - "8087:8087"
      - "8088:8088"
    hostname: woken
    networks:
      - woken-bridge
    depends_on:
      - chronos
      - db

  woken-validation:
    image: hbpmip/woken-validation:latest
    volumes:
      - ./woken-validation/config/application.conf:/opt/woken-validation/config/application.conf
      - ./woken-validation/lib:/opt/woken-validation/lib
    ports:
      - "8082"
    hostname: woken-validation
    networks:
      - woken-bridge
    depends_on:
      - woken

networks:
  woken-bridge:
    external:
      name: woken-bridge
