# Configuration taken from https://github.com/meltwater/docker-mesos

zookeeper:
  image: mesoscloud/zookeeper:3.4.6-centos-7
  ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"
  environment:
    SERVERS: 'server.1=127.0.0.1'
    MYID: '1'

mesosmaster:
  image: mesosphere/mesos-master:0.26.0-0.2.145.ubuntu1404
  net: host
  volumes:
    - /var/log/mesos/master
  environment:
    MESOS_ZK: 'zk://localhost:2181/mesos'
    MESOS_QUORUM: '1'
    MESOS_CLUSTER: 'local'
    MESOS_HOSTNAME: 'localhost'
    MESOS_LOG_DIR: '/var/log/mesos/master'

mesosslave:
  build: mesos-slave
  net: host
  privileged: true
  volumes:
    - /var/log/mesos/slave
    - /sys:/sys
# /cgroup is needed on some older Linux versions
#    - /cgroup:/cgroup
# /usr/bin/docker is needed if you're running an older docker version
#    - /usr/local/bin/docker:/usr/bin/docker:r
    - /var/run/docker.sock:/var/run/docker.sock:rw
  environment:
    MESOS_MASTER: 'zk://localhost:2181/mesos'
    MESOS_PORT: '5051'
    MESOS_LOG_DIR: '/var/log/mesos/slave'
    MESOS_CONTAINERIZERS: 'docker,mesos'
    MESOS_EXECUTOR_REGISTRATION_TIMEOUT: '5mins'
    MESOS_EXECUTOR_SHUTDOWN_GRACE_PERIOD: '90secs'
    MESOS_DOCKER_STOP_TIMEOUT: '60secs'
# If your workstation doesn't have a resolvable hostname/FQDN then $MESOS_HOSTNAME needs to be set to its IP-address
#    MESOS_HOSTNAME: 10.87.1.123

chronos:
  image: mesosphere/chronos:chronos-2.4.0-0.1.20151007110204.ubuntu1404-mesos-0.26.0-0.2.145.ubuntu1404
  command: '/usr/bin/chronos run_jar --http_port 4400 --zk_hosts localhost:2181 --master zk://localhost:2181/mesos'
  net: host

analyticsdb:
  image: postgres:9.4.5
  net: host
  volumes:
    - ./analytics-db/sql:/docker-entrypoint-initdb.d/
  environment:
    POSTGRES_PASSWORD: test

workflow:
  build: workflow
  net: host
  volumes:
    - ./workflow/config:/opt/workflow/config
    - ./workflow/lib:/opt/workflow/lib
