# Configuration taken from https://github.com/meltwater/docker-mesos
# https://github.com/containous/traefik/blob/master/examples/compose-marathon.yml

version: '2'
services:
  zookeeper:
    image: netflixoss/exhibitor:1.5.2
    hostname: zookeeper
    networks:
      - woken-bridge

  mesos_master:
    image: mesosphere/mesos-master:1.3.0
    hostname: mesosmaster
    volumes:
      - ./log/mesos/master:/var/log/mesos/master:rw
      - ./tmp/mesos/master:/var/tmp/mesos:rw
    networks:
      - woken-bridge
    environment:
      MESOS_PORT: 5050
      MESOS_ZK: 'zk://zookeeper:2181/mesos'
      MESOS_QUORUM: '1'
      MESOS_REGISTRY: 'in_memory'
      MESOS_CLUSTER: 'local'
      MESOS_HOSTNAME: 'mesosmaster.docker'
      MESOS_LOG_DIR: '/var/log/mesos/master'
    depends_on:
      - zookeeper

  mesos_slave:
    image: mesosphere/mesos-slave:1.3.0
    hostname: mesosslave
    privileged: true
    volumes:
      - ./log/mesos/slave:/var/log/mesos/slave:rw
      - ./tmp/mesos/slave:/var/tmp/mesos:rw
      - /sys:/sys
      #- /cgroup:/cgroup is it really needed for the demo? Not compatible with docker machine on MacOSX, try /sys/fs/cgroups...
      # /usr/bin/docker is needed if you're running an older docker version
      #- /usr/bin/docker:/usr/bin/docker:r
      - /var/run/docker.sock:/var/run/docker.sock:rw
    networks:
      - woken-bridge
    environment:
      MESOS_MASTER: 'zk://zookeeper:2181/mesos'
      MESOS_PORT: '5051'
      MESOS_LOG_DIR: '/var/log/mesos/slave'
      MESOS_WORK_DIR: '/var/tmp/mesos'
      MESOS_CONTAINERIZERS: 'docker,mesos'
      MESOS_EXECUTOR_REGISTRATION_TIMEOUT: '5mins'
      MESOS_EXECUTOR_SHUTDOWN_GRACE_PERIOD: '90secs'
      MESOS_DOCKER_STOP_TIMEOUT: '60secs'
      # If your workstation doesn't have a resolvable hostname/FQDN then $MESOS_HOSTNAME needs to be set to its IP-address
      MESOS_HOSTNAME: 'mesosslave.docker'
      MESOS_SWITCH_USER: 0
      # see bug resolution for "Failed to determine the hierarchy where the subsystem freezer is attached" at https://github.com/eBayClassifiedsGroup/PanteraS/issues/142
      MESOS_LAUNCHER: "posix"
    depends_on:
      - zookeeper
      - mesos_master

  chronos:
    image: mesosphere/chronos:v3.0.2
    command: '/usr/bin/chronos run_jar --http_port 4400 --zk_hosts zookeeper:2181 --master zk://zookeeper:2181/mesos'
    hostname: chronos
    ports:
      - "4400:4400"
      - "4401:4401"
    networks:
      - woken-bridge
    environment:
      PORT0: 4400
      PORT1: 4401
    depends_on:
      - zookeeper
      - mesos_slave

  # Expose the database to the host
  db:
    image: postgres:9.6.5-alpine
    ports:
      - "5432:5432"
    hostname: db
    networks:
      - woken-bridge
    environment:
      POSTGRES_PASSWORD: test

  wait_dbs:
    image: "waisbrot/wait"
    restart: "no"
    networks:
      - woken-bridge
    environment:
      TARGETS: "db:5432"
      TIMEOUT: 60

  create_dbs:
    image: "hbpmip/create-databases:1.0.0"
    restart: "no"
    networks:
      - woken-bridge
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_ADMIN_USER: postgres
      DB_ADMIN_PASSWORD: test
      DB1: meta
      USER1: meta
      PASSWORD1: metapwd
      DB2: features
      USER2: features
      PASSWORD2: featurespwd
      DB3: woken
      USER3: woken
      PASSWORD3: wokenpwd
      DB4: portal
      USER4: portal
      PASSWORD4: portalpwd
    depends_on:
      - db

  meta_db_setup:
    image: "hbpmip/sample-meta-db-setup:0.3.1"
    container_name: "meta-db-setup"
    restart: "no"
    networks:
      - woken-bridge
    environment:
      FLYWAY_HOST: db
      FLYWAY_PORT: 5432
      FLYWAY_DATABASE_NAME: meta
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: test
    depends_on:
      - db

  sample_db_setup:
    image: "hbpmip/sample-data-db-setup:0.4.0"
    container_name: "data-db-setup"
    restart: "no"
    networks:
      - woken-bridge
    environment:
      FLYWAY_HOST: db
      FLYWAY_PORT: 5432
      FLYWAY_DATABASE_NAME: features
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: test
    depends_on:
      - db

  woken_db_setup:
    image: "hbpmip/woken-db-setup:1.0.2"
    container_name: "woken-db-setup"
    restart: "no"
    networks:
      - woken-bridge
    environment:
      FLYWAY_HOST: db
      FLYWAY_PORT: 5432
      FLYWAY_DATABASE_NAME: woken
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: test
    depends_on:
      - db

  woken:
    image: hbpmip/woken
    volumes:
      - ./woken/config:/opt/woken/config
    ports:
      - "8087:8087"
      - "8088:8088"
    hostname: woken
    networks:
      - woken-bridge
    depends_on:
      - chronos
      - db

  woken_validation:
    image: hbpmip/woken-validation:2.0.2
    volumes:
      - ./woken-validation/config/application.conf:/opt/woken-validation/config/application.conf
    ports:
      - "8082:8082"
    hostname: woken-validation
    networks:
      - woken-bridge
    depends_on:
      - woken

  wait_woken:
    image: "waisbrot/wait"
    restart: "no"
    networks:
      - woken-bridge
    environment:
      TARGETS: "woken:8087"
      TIMEOUT: 60

  woken_test:
    build:
      context: ./woken-test
      dockerfile: Dockerfile
    networks:
      - woken-bridge
    depends_on:
      - woken

  portal_backend:
    image: "hbpmip/portal-backend:2.4.1"
    container_name: "backend-test"
    restart: "no"
    ports:
      - "65440:8080"
    networks:
      - woken-bridge
    environment:
      PORTAL_DB_URL: jdbc:postgresql://db:5432/portal
      PORTAL_DB_SERVER: db:5432
      PORTAL_DB_USER: portal
      PORTAL_DB_PASSWORD: portalpwd
      META_DB_URL: jdbc:postgresql://db:5432/meta
      META_DB_SERVER: db:5432
      META_DB_USER: meta
      META_DB_PASSWORD: metapwd
      FEATURES_DB_URL: jdbc:postgresql://db:5432/features
      FEATURES_DB_SERVER: db:5432
      FEATURES_DB_USER: features
      FEATURES_DB_PASSWORD: featurespwd
      FEATURES_DB_MAIN_TABLE: sample_data
      WOKEN_HOST: woken
      WOKEN_PORT: 8088
      WOKEN_AKKA_PATH: "/user/entrypoint"
      CONTEXT_PATH: /services
      AUTHENTICATION: 0
      FRONTEND_LOGIN_URL: http://frontend/services/login/hbp
      FRONTEND_AFTER_LOGIN_URL: http://frontend/home
      FRONTEND_AFTER_LOGOUT_URL: http://frontend/services/login/hbp
      WOKEN_HOST: woken
      WOKEN_PORT: 8088
      WOKEN_AKKA_PATH: "/user/entrypoint"
    depends_on:
      - db
      - woken

  wait_portal_backend:
    image: "waisbrot/wait"
    restart: "no"
    networks:
      - woken-bridge
    environment:
      - TARGETS=portal_backend:8080
    depends_on:
      - portal_backend

  frontend:
    image: hbpmip/portal-frontend:2.3.2
    depends_on:
      - portal_backend
    ports:
      - "80:80"
    environment:
      WORKER_PROCESSES: 1
      ERROR_LOG_LEVEL: warn
      PORTAL_VIRTUAL_HOST: frontend
      PORTAL_BACKEND_SERVER: portal_backend:8080
      PORTAL_BACKEND_CONTEXT: services
    networks:
      - woken-bridge

networks:
  woken-bridge:
    external:
      name: woken-bridge
