version: '2'

services:
  zookeeper:
    image: netflixoss/exhibitor:1.5.2
    hostname: zookeeper
    networks:
      - woken-bridge

  mesos_master:
    image: mesosphere/mesos-master:1.3.0
    hostname: mesosmaster
    volumes:
      - ./log/mesos/master:/var/log/mesos/master:rw
      - ./tmp/mesos/master:/var/tmp/mesos:rw
    networks:
      - woken-bridge
    environment:
      MESOS_PORT: 5050
      MESOS_ZK: 'zk://zookeeper:2181/mesos'
      MESOS_QUORUM: '1'
      MESOS_REGISTRY: 'in_memory'
      MESOS_CLUSTER: 'local'
      MESOS_HOSTNAME: 'mesosmaster.docker'
      MESOS_LOG_DIR: '/var/log/mesos/master'
    depends_on:
      - zookeeper

  mesos_slave:
    image: mesosphere/mesos-slave:1.3.0
    hostname: mesosslave
    privileged: true
    volumes:
      - ./log/mesos/slave:/var/log/mesos/slave:rw
      - ./tmp/mesos/slave:/var/tmp/mesos:rw
      - /sys:/sys
      - /cgroup:/cgroup
      # /usr/bin/docker is needed if you're running an older docker version
      #- /usr/bin/docker:/usr/bin/docker:r
      - /var/run/docker.sock:/var/run/docker.sock:rw
    networks:
      - woken-bridge
    environment:
      MESOS_MASTER: 'zk://zookeeper:2181/mesos'
      MESOS_PORT: '5051'
      MESOS_LOG_DIR: '/var/log/mesos/slave'
      MESOS_WORK_DIR: '/var/tmp/mesos'
      MESOS_CONTAINERIZERS: 'docker,mesos'
      MESOS_EXECUTOR_REGISTRATION_TIMEOUT: '5mins'
      MESOS_EXECUTOR_SHUTDOWN_GRACE_PERIOD: '90secs'
      MESOS_DOCKER_STOP_TIMEOUT: '60secs'
      # If your workstation doesn't have a resolvable hostname/FQDN then $MESOS_HOSTNAME needs to be set to its IP-address
      MESOS_HOSTNAME: 'mesosslave.docker'
      MESOS_SWITCH_USER: 0
      # see bug resolution for "Failed to determine the hierarchy where the subsystem freezer is attached" at https://github.com/eBayClassifiedsGroup/PanteraS/issues/142
      MESOS_LAUNCHER: "posix"
    depends_on:
      - zookeeper
      - mesos_master

  chronos:
    image: mesosphere/chronos:chronos-2.5.0-0.1.20170628182950.ubuntu1404-mesos-1.3.0
    command: '/usr/bin/chronos run_jar --http_port 4400 --zk_hosts zookeeper:2181 --master zk://zookeeper:2181/mesos'
    hostname: chronos
    networks:
      - woken-bridge
    ports:
      - 4400:4400
      - 8081:8081
    depends_on:
      - zookeeper
      - mesos_slave

  # Expose the database to the host, including the Docker container running the algorithms
  woken_db:
    image: "postgres:9.6.2-alpine"
    container_name: "woken-db"
    networks:
      - woken-bridge
    ports:
      - 65434:5432
    restart: unless-stopped
    environment:
      - POSTGRES_USER=woken
      - POSTGRES_PASSWORD=woken

  wait_dbs:
    image: "waisbrot/wait"
    networks:
      - woken-bridge
    links:
      - "woken_db:woken_db"
    environment:
      - TARGETS=woken_db:5432

  # Use the latest image built as this is what is under test
  woken_db_setup:
    image: "hbpmip/woken-db-setup:b22cb6c"
    networks:
      - woken-bridge
    container_name: "woken-db-setup"
    environment:
      - FLYWAY_DBMS=postgresql
      - FLYWAY_HOST=db
      - FLYWAY_PORT=5432
      - FLYWAY_DATABASE_NAME=woken
      - FLYWAY_USER=woken
      - FLYWAY_PASSWORD=woken
    links:
     - "woken_db:db"

  # Expose the database to the host, including the Docker container running the algorithms
  sciencedb:
    image: postgres:9.4.5
    container_name: "science_db"
    networks:
      - woken-bridge
    ports:
      - 65432:5432
    volumes:
      - ./sample-datasets-db/sql:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: test

  # Expose the database to the host
  metadb:
    image: postgres:9.4.5
    networks:
     - woken-bridge
    ports:
      - 65433:5432
    volumes:
      - ./sample-datasets-db/meta/sql:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: test

  woken-validation:
    networks:
      - woken-bridge
    extra_hosts:
     - "woken:${HOST}"
    image: hbpmip/woken-validation:AutoML
    volumes:
      - ./woken/config/validation/application.conf:/opt/woken-validation/config/application.conf
      - ./woken-validation/lib:/opt/woken-validation/lib
    ports:
      - 8082:8082

networks:
  woken-bridge:
    external:
      name: woken-bridge