# Configuration taken from https://github.com/meltwater/docker-mesos

zookeeper:
  image: mesoscloud/zookeeper:3.4.6-centos-7
  net: host
  ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"
  environment:
    SERVERS: 'server.1=127.0.0.1'
    MYID: '1'

mesosmaster:
  image: mesosphere/mesos-master:0.28.1
  net: host
  volumes:
    - /var/log/mesos/master
  environment:
    MESOS_ZK: 'zk://localhost:2181/mesos'
    MESOS_QUORUM: '1'
    MESOS_CLUSTER: 'local'
    MESOS_HOSTNAME: 'localhost'
    MESOS_LOG_DIR: '/var/log/mesos/master'

mesosslave:
  build: mesos-slave
  net: host
  privileged: true
  volumes:
    - /var/log/mesos/slave
    - /sys:/sys
# /cgroup is needed on some older Linux versions
#    - /cgroup:/cgroup
# /usr/bin/docker is needed if you're running an older docker version
#    - /usr/local/bin/docker:/usr/bin/docker:r
    - /var/run/docker.sock:/var/run/docker.sock:rw
  environment:
    MESOS_MASTER: 'zk://localhost:2181/mesos'
    MESOS_PORT: '5051'
    MESOS_LOG_DIR: '/var/log/mesos/slave'
    MESOS_CONTAINERIZERS: 'docker,mesos'
    MESOS_EXECUTOR_REGISTRATION_TIMEOUT: '5mins'
    MESOS_EXECUTOR_SHUTDOWN_GRACE_PERIOD: '90secs'
    MESOS_DOCKER_STOP_TIMEOUT: '60secs'
# If your workstation doesn't have a resolvable hostname/FQDN then $MESOS_HOSTNAME needs to be set to its IP-address
    MESOS_HOSTNAME: 127.0.0.1

chronos:
  image: mesosphere/chronos:chronos-2.5.0-0.1.20160223054243.ubuntu1404-mesos-0.27.1-2.0.226.ubuntu1404
  command: '/usr/bin/chronos run_jar --http_port 4400 --zk_hosts localhost:2181 --master zk://localhost:2181/mesos'
  net: host
  ports:
    - "4400:4400"

# Expose the database to the host, including the Docker container running the algorithms
woken_db:
  image: "postgres:9.6.2-alpine"
  container_name: "woken-db"
  net: bridge
  ports:
    - "65434:5432"
  restart: unless-stopped
  environment:
    - POSTGRES_USER=woken
    - POSTGRES_PASSWORD=woken

wait_dbs:
  image: "waisbrot/wait"
  links:
    - "woken_db:woken_db"
  environment:
    - TARGETS=woken_db:5432

# Use the latest image built as this is what is under test
woken_db_setup:
  image: "hbpmip/woken-db-setup:latest"
  container_name: "woken-db-setup"
  environment:
    - FLYWAY_DBMS=postgresql
    - FLYWAY_HOST=db
    - FLYWAY_PORT=5432
    - FLYWAY_DATABASE_NAME=woken
    - FLYWAY_USER=woken
    - FLYWAY_PASSWORD=woken
  links:
   - "woken_db:db"

# Expose the database to the host, including the Docker container running the algorithms
sciencedb:
  image: postgres:9.4.5
  net: bridge
  ports:
    - "65432:5432"
  volumes:
    - ./sample-datasets-db/sql:/docker-entrypoint-initdb.d/
  environment:
    POSTGRES_PASSWORD: test

# Expose the database to the host
metadb:
  image: postgres:9.4.5
  net: bridge
  ports:
    - "65433:5432"
  volumes:
    - ./sample-datasets-db/meta/sql:/docker-entrypoint-initdb.d/
  environment:
    POSTGRES_PASSWORD: test

woken-validation:
  image: hbpmip/woken-validation:latest
  net: host
  volumes:
    - ./woken/config/validation/application.conf:/opt/woken-validation/config/application.conf
  ports:
    - "8082:8082"