#sudo: true
#services:
# - docker

#before_install:
# - docker pull thomastoye/kairosdb-scala-driver-it

language: scala

scala:
 - 2.11.8

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

script:
  # Your normal script
  - sbt ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M clean coverage test

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
env:
  global: []
  #- secure: hwSS

after_success:
  #- '[[ $TRAVIS_BRANCH == "master" ]] && { sbt publish; };'
  - "sbt coverageReport coveralls"
