#sudo: true
#services:
# - docker

#before_install:
# - docker pull thomastoye/kairosdb-scala-driver-it

sudo: required
dist: trusty
language: scala

scala:
 - 2.11.11

jdk:
  - oraclejdk8

addons:
  # https://github.com/travis-ci/travis-ci/issues/5227#issuecomment-165131913
  hosts:
    - woken
  hostname: woken

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_script:
  - jdk_switcher use $JDK

script:
  # Your normal script
  # TODO: put back coverage
  - sbt ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M clean test

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
env:
  global: []
  #- secure: hwSS

after_success:
  #- '[[ $TRAVIS_BRANCH == "master" ]] && { sbt publish; };'
  - "sbt coverageReport coveralls"
notifications:
  webhooks:
    urls:
    - 'https://webhook.atomist.com/travis'
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
